
import java.awt.Color;

public class GUI_Register extends javax.swing.JFrame {

    public static String nombre, contrasena, correo;
    public static String mensaje;

    public GUI_Register() {
        initComponents();
        jPanel1.setFocusable(true);
        TextNombre.setForeground(Color.GRAY);
        TextCorreo.setForeground(Color.GRAY);
        TextContrasena.setForeground(Color.GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextNombre = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        TextCorreo = new javax.swing.JTextField();
        TextContrasena = new javax.swing.JTextField();
        lblMensaje = new javax.swing.JLabel();
        bAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel3.setText("REGISTRO DE USUARIO");

        TextNombre.setText("Nombres y apellidos");
        TextNombre.setToolTipText("");
        TextNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextNombreFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(TextNombre);
        TextNombre.getAccessibleContext().setAccessibleParent(jPanel1);

        jButton1.setFont(new java.awt.Font("Impact", 1, 15)); // NOI18N
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TextCorreo.setText("Correo electrónico");
        TextCorreo.setToolTipText("");
        TextCorreo.setMinimumSize(new java.awt.Dimension(66, 26));
        TextCorreo.setName(""); // NOI18N
        TextCorreo.setPreferredSize(new java.awt.Dimension(140, 26));
        TextCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextCorreoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextCorreoFocusLost(evt);
            }
        });

        TextContrasena.setText("Contraseña");
        TextContrasena.setToolTipText("");
        TextContrasena.setMinimumSize(new java.awt.Dimension(66, 26));
        TextContrasena.setName(""); // NOI18N
        TextContrasena.setPreferredSize(new java.awt.Dimension(140, 26));
        TextContrasena.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextContrasenaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TextContrasenaFocusLost(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Impact", 1, 15)); // NOI18N

        bAtras.setFont(new java.awt.Font("Impact", 1, 15)); // NOI18N
        bAtras.setText("Atrás");
        bAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(155, 155, 155))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(TextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAtras)
                .addGap(17, 17, 17)
                .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        TextCorreo.getAccessibleContext().setAccessibleName("");
        TextCorreo.getAccessibleContext().setAccessibleDescription("text/plain");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        nombre = TextNombre.getText();
        contrasena = TextContrasena.getText();
        correo = TextCorreo.getText();
        Register.Post_JSON();
        lblMensaje.setText(mensaje);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreFocusLost
        // TODO add your handling code here:
        if (TextNombre.getText().trim().equals("")) {
            TextNombre.setText("Nombres y apellidos");
        }
        TextNombre.setForeground(Color.GRAY);


    }//GEN-LAST:event_TextNombreFocusLost

    private void TextNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextNombreFocusGained
        // TODO add your handling code here:
        if (TextNombre.getText().trim().equals("Nombres y apellidos")) {
            TextNombre.setText("");
        }
        lblMensaje.setText("");
        TextNombre.setForeground(Color.BLACK);
    }//GEN-LAST:event_TextNombreFocusGained

    private void TextCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCorreoFocusLost
        // TODO add your handling code here:
        if (TextCorreo.getText().trim().equals("")) {
            TextCorreo.setText("Correo electrónico");
        }
        TextCorreo.setForeground(Color.GRAY);
    }//GEN-LAST:event_TextCorreoFocusLost

    private void TextCorreoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextCorreoFocusGained
        // TODO add your handling code here:
        if (TextCorreo.getText().trim().equals("Correo electrónico")) {
            TextCorreo.setText("");
            
        }
        lblMensaje.setText("");
        TextCorreo.setForeground(Color.BLACK);
    }//GEN-LAST:event_TextCorreoFocusGained

    private void TextContrasenaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextContrasenaFocusLost
        // TODO add your handling code here:
        if (TextContrasena.getText().trim().equals("")) {
            TextContrasena.setText("Contraseña");
        }
        TextContrasena.setForeground(Color.GRAY);
    }//GEN-LAST:event_TextContrasenaFocusLost

    private void TextContrasenaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextContrasenaFocusGained
        // TODO add your handling code here:
        if (TextContrasena.getText().trim().equals("Contraseña")) {
            TextContrasena.setText("");
            
        }
        lblMensaje.setText("");
        TextContrasena.setForeground(Color.BLACK);
    }//GEN-LAST:event_TextContrasenaFocusGained

    private void bAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAtrasActionPerformed
        // TODO add your handling code here:
        new GUI_Main().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bAtrasActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUI_Register().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextContrasena;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextPane TextNombre;
    private javax.swing.JButton bAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables
}
